version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    # depends_on:
      # - postgres
    environment:
      AWS_ACCESS_KEY_ID:"${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY:"${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION:"${AWS_REGION}"
      AWS_BUCKET:"${AWS_BUCKET}"
      SHUTTERSTOCK_CLIENT_ID:"${SHUTTERSTOCK_CLIENT_ID}"
      SHUTTERSTOCK_SECRET:"${SHUTTERSTOCK_SECRET}"
      # DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos